name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:10.16.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Install NPM dependencies
        run: npm install
      - name: Restore lib dir
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Test
        run: npm test
